### ISSUE TITLE
Don't reveal Hypixel API key

### ISSUE THREAD

**Issue by fdshfghdghgfhg** [mdashlw/ranked-who#1]
Make api key not publicly revealed, but getting replaced by `Gradle replace tokens system`.

Suggested change in `Reference.kt`:

```kotlin
val API_KEY: UUID = UUID.fromString("@HYPIXEL_API_KEY@")
```

Then in Gradle build script replace this token by CI env variable.

It would make harder to see it, probably?

Maybe even introduce string obfuscation??

**Comment by mdashlw** [comment]
Decided to force user to type their own key.
